spring:
  application:
    name: order-service
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: orders-microservices
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    admin:
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8081

